name: Upload localization strings to CurseForge

on: 
  - workflow_call
  - workflow_dispatch
  - pull_request

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Upload localizations
        uses: p3lim/curseforge-localizations@v1
        env:
          CF_PROJECT_ID: 1055837
          CF_API_KEY: ${{ secrets.CF_API_KEY }}